[package]
name = "brenobattaglin-com"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "DomTokenList",
    "Storage",
    "IntersectionObserver",
    "IntersectionObserverInit",
    "IntersectionObserverEntry",
    "ScrollToOptions",
    "ScrollBehavior",
    "DomRect",
    "Event",
    "EventTarget",
    "HtmlElement",
    "Node",
    "NodeList",
] }
js-sys = "0.3"
console_error_panic_hook = "0.1"

[profile.dev]
debug = 1

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
