services:
  app:
    container_name: brenobattaglin.com
    image: brenobattaglin.com:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_PORT=5173
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

volumes:
  node_modules:
    name: brenobattaglin.com_node_modules

networks:
  default:
    name: brenobattaglin.com_default
